# Generated by Django 4.2.2 on 2023-06-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educational', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='votes',
            field=models.IntegerField(default=0),
        ),
    ]
